### ISSUE TITLE
Add space to after tags field is better when create new post

### ISSUE THREAD

**Issue by warrenwx** [hexojs/hexo-starter#32]
- hexo new post "xxx"
- hexo generate

```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
    ^
    at generateError (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1046:9)
    at composeNode (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/opt/github_io/warrenwx_hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at parseYAML (/opt/github_io/warrenwx_hexo/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/opt/github_io/warrenwx_hexo/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/opt/github_io/warrenwx_hexo/node_modules/hexo/lib/plugins/processor/post.js:52:20)
    at tryCatcher (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/github_io/warrenwx_hexo/node_modules/bluebird/js/release/promise.js:614:10)
```
- cause
  A space is missing after the semicolon of tag fileds of the "new post" auto genrated by hexo.

**Comment by rangerz** [comment]
Fixed in https://github.com/hexojs/hexo-starter/pull/67
